### PR TITLE
added datasets 831-843; providers 134,346-353

### PR DESCRIPTION
**Pull request by andrewhnorris**

### CODE REVIEW

**Review by ceteri — CHANGES_REQUESTED** [review]
hi @andrewhnorris , looks like `dataset-832` and `dataset-833` are duplicates?

**Comment by andrewhnorris** [comment]
@ceteri, 
I removed dataset-833 (not referenced in partitions). Is this PR up-to-date and ready to merge, or should I close it and submit a new PR?

**Review by ceteri — CHANGES_REQUESTED** [review]
Hi @andrewhnorris ,

Looks good except that `dataset-840` and `dataset-841` had the same title and URL.  Probably the `dataset-841` was about an NYC Alcohol Abuse study?

**Review by ceteri — APPROVED** [review]
Great, thanks!

**Pull request merged**
