### PR TITLE
dataset_provider_updates

### PR DESCRIPTION
**Pull request by menoah**
- added datasets  730-734
-added providers 314, 316, 317

### CODE REVIEW

**Comment by ceteri** [comment]
Hi @menoah, is there a duplicate `University of Rhode Island` in the providers?

```
    {
        "id": "provider-316",
        "title": "University of Rhode Island",
        "roc": "013ckk937"
    },
    {
        "id": "provider-317",
        "title": "University of Rhode Island",
        "roc": "013ckk937"
    }
```

**Review by ceteri — CHANGES_REQUESTED** [review]
Looks like a duplicate University of Rhode Island in the providers --
I'll add more in comments

**Comment by menoah** [comment]
> Looks like a duplicate University of Rhode Island in the providers --
> I'll add more in comments

Yes, so sorry, let me fix that

**Comment by menoah** [comment]
> Looks like a duplicate University of Rhode Island in the providers --
> I'll add more in comments

Revised the Duplicate with the proper information

{
        "id": "provider-316",
        "title": "University of Rhode Island",
        "roc": "013ckk937"
    },
    {
        "id": "provider-317",
        "title": "University of Florida",
        "roc": "02y3ad647"
    }

**Review by ceteri — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
