### PR TITLE
started going through chapin hall list

### PR DESCRIPTION
**Pull request by benjamin-feder**
started adding a bunch of datasets

### CODE REVIEW

**Review by ceteri — CHANGES_REQUESTED** [review]
The most recent PR by @srand525 ended at `dataset-060`:
```
        "id": "dataset-060",
        "provider": "U.S. Department of Agriculture",
        "title": "Store Tracking and Redemption System",
```

This PR picks up at `dataset-051`:
```
        "id": "dataset-051",
        "provider":"Intitute for Research on Poverty at the University of Wisconsin–Madison",
        "title": "Multi-Sample Person File",
```

So there's an offset problem.  Is it straightforward to bump the ID numbering in this PR up +10 ?

**Comment by benjamin-feder** [comment]
There aren't any repeated entries, correct?

**Comment by ceteri** [comment]
No, I didn't find any repeats.
Later I'll write a quick script to attempt to identify repeats.

**Comment by benjamin-feder** [comment]
so is this good to go outside of conflicts?

**Comment by benjamin-feder** [comment]
^asking because I have another few that I've added locally on my branch

**Pull request closed without merging**
