### PR TITLE
dataset_updates

### PR DESCRIPTION
**Pull request by menoah**

### CODE REVIEW

**Review by ceteri — CHANGES_REQUESTED** [review]
There are two problems:

  - `United States Geological Survey` is a duplicate -- already in `providers.json`
  - the indexing conflicts with the previous pull request, and most of the changes require renumbering

**Comment by menoah** [comment]
> There are two problems:
> 
> * `United States Geological Survey` is a duplicate -- already in `providers.json`
> * the indexing conflicts with the previous pull request, and most of the changes require renumbering

Sorry about that:
* Just updated providers.json to remove the duplicate entry (United States Geological Survey) 
* Renumbered the provider ids for the remaining entries. I also reflected these changes for the recent datasets added on datasets.json
* Also renamed the title of provider-278 to "National Centre for Longitudinal Data Dataverse"

**Comment by ceteri** [comment]
Thank you @menoah 

Although there are still merge conflicts in the `providers.json` with several entries that have overlapping IDs from the previous PR.

You might try updating your branch from current master first, then applying the new numbering -- before committing again.

**Comment by ceteri** [comment]
This is close -- though there are still two missing providers:

```
(base) derwen:~/src/RCDatasets$ ./test.py
..unknown providers: ['provider-279', 'provider-280']
F
```

**Comment by srand525** [comment]
Hi Marcos
a few issues that came up while running the test...
```..unknown providers: ['provider-279', 'provider-280', 'provider-281', 'provider-282', 'provider-283', 'provider-284', 'provider-285', 'provider-286', 'provider-287', 'provider-288', 'provider-289']
F
650 datasets loaded

279 providers loaded
.....E
======================================================================
ERROR: test_unique_titles (__main__.TestVerifyDatasets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 96, in test_unique_titles
    raise Exception("{}: duplicate title {}".format(dataset["id"], title))
Exception: dataset-652: duplicate title National Elevation Dataset

======================================================================
FAIL: test_enum_providers (__main__.TestVerifyDatasets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 134, in test_enum_providers
    self.assertTrue(len(unknowns) < 1)
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by ceteri** [comment]
looks good now

**Pull request merged**
